[package]
name = "cast-rs"
version = "0.1.0"
authors = ["beautifularea <beautifularea@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
typename = "0.1.1"

[lib]
name = "cast_rs"
path = "src/lib.rs"

